# Generated by Django 3.1 on 2022-07-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0003_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.TextField(default=None)),
            ],
        ),
    ]
