# Generated by Django 3.1 on 2022-07-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0004_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='user',
            field=models.TextField(default=None),
        ),
    ]
