# Generated by Django 3.1 on 2022-07-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0005_gender_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='nutrition',
            field=models.CharField(default='Carbs', max_length=200),
        ),
    ]
